name = "asur" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "waime.tech"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.waime.tech"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.waime.tech"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.waime.tech"
custom_domain = true
[[routes]]
pattern = "api.instagram.com.waime.tech"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.waime.tech"
custom_domain = true

[vars]
UUID = "530d3f03-06ae-4c8a-9edf-cab933f869d2"
